steps:
  # Install dependencies and run tests
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
  - name: "gcr.io/cloud-builders/npm"
    args: ["test"]
    env:
      - "CI=true" # To ensure Jest runs in CI mode if it has specific CI behavior

  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/hello-express-service:${_TAG}",
        ".",
      ]

  # Push the container image to Google Container Registry (GCR)
  # You can also use Artifact Registry: asia-south1-docker.pkg.dev/$PROJECT_ID/[REPOSITORY_NAME]/hello-express-service:${_TAG}
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "gcr.io/$PROJECT_ID/hello-express-service:${_TAG}",
      ]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: [
        "run",
        "deploy",
        "hello-express-service",
        "--image",
        "gcr.io/$PROJECT_ID/hello-express-service:${_TAG}",
        "--region",
        "asia-south1",
        "--platform",
        "managed", # or 'gke', 'anthos'
        "--allow-unauthenticated", # Allows public access, remove if not needed
      ]

images:
  - "gcr.io/$PROJECT_ID/hello-express-service:${_TAG}"

# Define substitutions with default values
substitutions:
  _TAG: "${SHORT_SHA}"  # Use SHORT_SHA as default, fallback to 'latest' if needed

options:
  logging: CLOUD_LOGGING_ONLY
